directories:
  output: release
  buildResources: build
appId: gg.launcherexe.glop
productName: LauncherExe
files:
  - filter:
      - dist/**/*
      - out/**/*
win:
  target: nsis
  icon: build/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
publish:
  - provider: github
    owner: glopmts
    repo: LauncherExe
    private: false
electronVersion: 39.8.0
